Chat comp talk
MrStnr21/botkits-14-frontend pull request #137
Opened 2023-10-27 10:39 UTC by lighterboiii

@AlekseyShaydullin просто посмотреть)

2023-11-06 09:51 UTC, lighterboiii commented
@AlekseyShaydullin сделал рефактор стилей, внёс небольшие правки, прошу проверить

2023-11-08 12:57 UTC, AlekseyShaydullin requested changes

2023-11-08 12:57 UTC, AlekseyShaydullin commented on src/components/dialog/dialog.tsx
> +                    <SearchIcon size="large" />
**При нажатии на кнопку перерисовывается вся страница. Надо бы Мемоизацию применить.**

2023-11-08 12:57 UTC, AlekseyShaydullin commented on src/components/dialog/dialog.tsx
> +          <InputMessage onChange={(e) => setInputValue(e.target.value)} />
**При добавлении символа в текст-ариа происходит перерисовка всей страницы. Необходимо сделать мемоизацию**

2023-11-08 15:28 UTC, merged