Chat-Comp-Сontacts: добавить блок с диалогами слева в чате
MrStnr21/botkits-14-frontend pull request #170
Opened 2023-11-03 22:24 UTC by seliveren

+ по поиску и фильтрации попробую сделать после первой итерации во время правок;
+ отображение времени, когда пришло сообщение (timeAgo) - немного в ином формате, чем на макете, в связи с тем, что в используемой библиотеке это отображается именно так, как есть в проекте. В теории можно поискать ещё библиотеки, но, например, moment.js уже не поддерживается, если не ошибаюсь, и шанс найти нормальную - по-моему - не очень высок... Можно и самой написать что-то, но это упороться...
+ по поводу ручек у Славы запросила, пока сделала на своих моковых данных всё;

2023-11-04 15:21 UTC, AlekseyShaydullin requested changes

2023-11-04 15:21 UTC, AlekseyShaydullin commented on src/components/chat/dialogs/dialogs.tsx
> +      <InputDialogsues />
**Выпадающего меню должно закрываться при клике на оверлэй. И при нажатии кнопки esc**

2023-11-04 15:21 UTC, AlekseyShaydullin commented on src/utils/getTimeAgo.tsx
> -export default function getTimeAgo(date: Date) {
**Так там же функцию можно самому написать, это же не сложно, зачем библу целую подтягивать сюда, тем более если библы дают не тот результат который нам нужен?
Чекаешь актуальное время. Сравниваешь со временем сообщения. Если разница больше 24 часов, то выдаешь дату через точки. Если меньше 24 часов вычитаешь одно из другого и получается количество минут, если больше 60 минут, то выдаешь количество часов.**

2023-11-05 09:22 UTC, seliveren commented on src/components/chat/dialogs/dialogs.tsx
> +      <InputDialogsues />
Так как это не мой компонент, мне нужно время, чтобы вникнуть - можно это вынести в отдельную задачу и назначить сразу на меня или же держать этот PR отрытым, но тогда Слава не сможет пока что приступить к сбору страницы.

2023-11-05 09:24 UTC, seliveren commented on src/components/chat/dialogs/dialogs.tsx
> +  const testData = [
P.S. то, что приходит к нам по сообщениям, ещё пока точно неизвестно до конца, поэтому оставила свои моковые данные.

2023-11-05 09:25 UTC, seliveren commented on src/utils/getTimeAgo.tsx
> -export default function getTimeAgo(date: Date) {
Ответила в дискорде. Предлагаю пока что оставить это на работы по рефакторингу.

2023-11-05 09:32 UTC, seliveren commented on src/components/chat/dialogs/dialogs.tsx
> +  const testData = [
создан файл utils/mockData.ts

2023-11-08 07:52 UTC, merged