Chat comp popup
MrStnr21/botkits-14-frontend pull request #184
Opened 2023-11-06 23:58 UTC by RUS29TAM

feat: компонент модального окна с функцией добавления файлов
1. реализован функционал добавления файлов с помощью drgag & drop
2. реализован функционал добавления файлов посредством открытия отдельного окна при клике на зону drgag & drop
3. d&d зона стилизована - при наведении курсора левая часть (зона d&d) модального окна пульсирует.

2023-11-07 09:49 UTC, AlekseyShaydullin requested changes

2023-11-07 09:49 UTC, AlekseyShaydullin commented on src/components/popups/chat-comp-popup/chat-comp-popup.tsx
**Логика компонента не заведена на кнопку скрепка в компоненте InputMessage**
![Снимок экрана 2023-11-07 124454](https://github.com/MrStnr21/botkits-14-frontend/assets/101606512/80fbe107-ba18-42a6-836a-a2debc929be5)

2023-11-07 09:49 UTC, AlekseyShaydullin commented on src/components/popups/chat-comp-popup/chat-comp-popup.tsx
> +const FileItem: FC<FileItemProps> = ({ item, index, handleRemoveItem }) => {
**Это отдельный UI компонент. У него должна быть своя папка с логикой и стилями**

2023-11-07 09:49 UTC, AlekseyShaydullin commented on src/components/popups/chat-comp-popup/chat-comp-popup.tsx
> +export function useDrag<Element extends HTMLElement>(
**Данную функцию хорошо бы вынести в утилиты в файл хелперы**

2023-11-07 14:22 UTC, RUS29TAM commented on src/components/popups/chat-comp-popup/chat-comp-popup.tsx
> +const FileItem: FC<FileItemProps> = ({ item, index, handleRemoveItem }) => {
@AlekseyShaydullin done

2023-11-07 14:23 UTC, RUS29TAM commented on src/components/popups/chat-comp-popup/chat-comp-popup.tsx
> +export function useDrag<Element extends HTMLElement>(
@AlekseyShaydullin done

2023-11-07 14:23 UTC, RUS29TAM commented
@AlekseyShaydullin все поправил.

2023-11-07 19:26 UTC, AlekseyShaydullin requested changes

2023-11-08 02:20 UTC, RUS29TAM commented on src/ui/file-item/file-item.tsx
@AlekseyShaydullin done

2023-11-09 19:49 UTC, RUS29TAM commented
@AlekseyShaydullin resolve conflicts

2023-11-13 10:27 UTC, merged