Универсальный элемент меню и выпадающее меню
MrStnr21/botkits-14-frontend pull request #229
Opened 2023-11-19 19:25 UTC by DorkEMK

- компонент меню: может быть обычный, с иконкой, с чеком и дополнительно стилизованный. С кликом.
- выпадающее меню, основанное на компоненте. Также может принимать дополнительную стилизацию

Дополнительная стилизация реализована через пропс, принимающий имя класса, что позволяет пользователю компонента самому задать размер, позиционирование, адаптивность, а также перезаписать дефолтные свойства (добавлен комментарий с подсказкой, как это сделать).

Заодно переписан на Menu компонент на странице статистики, потому что я на нём тестировала поведение))

Функциональность мультичека не протестирована, возможно нужно будет допиливать. Концепция была - оставить максимум логики за пределами компонентов и отдать им только рендер

2023-11-21 11:02 UTC, AlekseyShaydullin requested changes

2023-11-21 12:33 UTC, DorkEMK commented on src/components/date-selector/date-selector.tsx
>    defaultValue: string;
Всё так! в menu можно прокидывать опции с icon, а можно обычные. Поэтому там опциональный пропс. В компоненте DateSelector иконки в меню не нужны

2023-11-21 12:36 UTC, DorkEMK commented on src/ui/menu-item/menu-item.tsx
> +const renderIcon = (hasIcon: boolean, icon: string | undefined) => {
Артефакт :')

2023-11-21 20:16 UTC, DorkEMK commented on src/components/date-selector/date-selector.tsx
как раз нужен, функция должна использовать свой аргумент, а не внешнюю переменную) Спасибо за внимательность!

2023-11-21 20:20 UTC, DorkEMK commented
Сделала отдельные хуки для закрытия по esc и для закрытия по клику снаружи, чтобы их можно было использовать по отдельности. А затем собрала в один хук, потому что скорее всего они часто будут вместе)

Общий тип Ref возможно стоит вынести в utils/types, чтобы не объявлять много раз, правда, мне кажется, что там какой-то немножко склад любых типов окажется

Ref типизирован через <HTMLDivElement>, то есть <button ref={ref}> скорее всего будет ругаться. Я бы предпочла что-то более универсальное, но недостаточно сильна в тайпскрипте. Скажем так, место применения (<div ref={ref}>) затребовало такую типизацию, пошла от неё. Выпадающий список - div, так что надеюсь проблем не поймаем

2023-11-24 12:57 UTC, AlekseyShaydullin commented on src/components/date-selector/date-selector.tsx
>    defaultValue: string;
Тут комментарий был не про опциональный пропс, а про то что в родительском компоненте, который и получает пропс **options** отсутствовал опциональный пропс **icon**. Сейчас уже все хорошо

2023-11-24 13:37 UTC, merged